version: "3.7"

services:
   minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    volumes:
    - minio1:/data
    ports:
    - "9000:9000"
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ""
      MINIO_SECRET_KEY: ""
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes: 
  minio1: